### ISSUE TITLE
API for getting keys by pattern

### ISSUE THREAD

**Issue by wclr** [kahlil/cycle-storage-driver#14]
I think thiere is need in getting keys by pattern. Its quite easy 
As storage keys can be taken with `Object.keys(localStorage)`

**Comment by khalillechelt** [comment]
What do you mean with "by pattern"?

**Comment by wclr** [comment]
Well it could get all the keys by defalut, but also as sugar could take string or RegExp on which it would test key and return only keys matched.

**Comment by laszlokorte** [comment]
I think it would be useful if you could provide a concrete use case you have in mind.

**Comment by wclr** [comment]
Well for example you are keeping some items with keys `document_{id}`, and you want to get all the documents available in storage, you either need to keep some where ids list, you you can filter the key names to match the pattern `document_`.

**Comment by khalillechelt** [comment]
Hi sorry for the long silence.

I don't feel this feature belongs into the driver. The driver just implements the storage API as is.

**Comment by khalillechelt** [comment]
Closing this for now.
