### ISSUE TITLE
Support Cycle.js Diversity

### ISSUE THREAD

**Issue by TylorS** [kahlil/cycle-storage-driver#15]
Add support for the next version of Cycle.js which is stream agnostic. Possibly porting to xstream (as the other core drivers are doing) or possibly in a stream agnostic fashion like the history driver.

**Comment by khalillechelt** [comment]
:+1: 

I guess porting to xstream for now would be appropriate?

**Comment by TylorS** [comment]
That would likely be the easiest path forward :)

Let me know if you have any questions or need any guidance, I'd be more than happy to assist you.

**Comment by khalillechelt** [comment]
Will do! Thank you. I am excited to use xstream 😀 !

**Comment by khalillechelt** [comment]
Oh by the way I saw that @staltz is taking care of this already in https://github.com/cyclejs/storage/tree/diversity so I am closing this issue.
