### ISSUE TITLE
Cycle diversity support?

### ISSUE THREAD

**Issue by eskhool** [kahlil/cycle-storage-driver#18]
Is this on the roadmap?

**Comment by jvanbruegge** [comment]
I rewrote this driver with support for cycle diversity, you can find it here: https://github.com/SuperManitu/cyclejs-storage

just `npm i -S cyclejs-storage` and you are good to go

**Comment by ntilwalli** [comment]
It already exists under the diversity branch.  Install via: `npm install --save @cycle/storage@3.0.0-rc3`

I've created an issue https://github.com/cyclejs/storage/issues/19

**Comment by jvanbruegge** [comment]
Not really relevant any more
