### ISSUE TITLE
Merge diversity to master and release latest version to npm

### ISSUE THREAD

**Issue by ntilwalli** [kahlil/cycle-storage-driver#19]
Currently the latest version of this driver is hidden in the `diversity` branch and accessing that version requires explicitly using version numbers in npm via `npm install --save @cycle/storage@3.0.0-rc3`.  It's confusing.

**Comment by jessaustin** [comment]
When I install that version I get an unmet peer dependency on `xstream@4.x.x`, since I'm using `xstream` v5. I'll let you know if it works anyway...

**Comment by staltz** [comment]
Done
