### ISSUE TITLE
Updates from Storage

### ISSUE THREAD

**Issue by TylorS** [kahlil/cycle-storage-driver#7]
First of all the implementation looks very clean @kahlil, great work!

However my concern is that with the current implementation, storage.get*() returns Rx.Observable.just(*), which disallows the ability to get updates from storage.

``` js
function main({storage}) {
  storage.getItem('key') // always equals first value
}
```

 Unless you're calling it in another function which is imperative and makes me question why I wouldn't just call localStorage.getItem directly.

``` js
function main({DOM, storage}) {
  DOM.select('a').events('click')
    .flatMap(ev => storage.getItem(ev.target.value)) // or something similar
}
```

Maybe I missed something, but this seems to be the current behavior at first glance.

**Comment by khalillechelt** [comment]
Hey @TylorS that makes sense. So I just use [`.from()`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/from.md) right?

**Comment by khalillechelt** [comment]
Something like:

``` js
export default {
  // For localStorage.
  local: {
    key(n) {
      // Function returning Observable of the nth key.
      return Rx.Observable.from([localStorage.key(n)])
    },
    // Function returning Observable of values.
    getItem(key) {
      return Rx.Observable.from([localStorage.getItem(key)])
    },
  },
  // For sessionStorage.
  session: {
    // Function returning Observable of the nth key.
    key(n) {
      return Rx.Observable.from([sessionStorage.key(n)])
    },
    // Function returning Observable of values.
    getItem(key) {
      return Rx.Observable.from([sessionStorage.getItem(key)])
    },
  },
}
```

?

**Comment by khalillechelt** [comment]
Oh, @TylorS are you thinking of storage updates flowing from getItem automatically when something changes?

This is not necessarily something you always want though. Often you just want to write to localStorage when something happens and read out of localStorage to rehydrate the app on load or reload.

Do you have an idea how to do the continuous update thing? I have to think about this for a bit...

**Comment by staltz** [comment]
@kahlil to get the "read out of localStorage only once", the developer can use just `storage.getItem('key').take(1)`. So I also agree to support the more general case which emits all updates.

**Comment by TylorS** [comment]
That's effectively the same thing as Rx.Observable.just(), since Rx.Observable.from() with an array of a single item will only produce a single response.

I don't think a driver is really needed if you are only looking for finite information.It would be much easier just to do

``` js
run(main, {
  storageItem: () => localStorage.getItem('key')
})
```

With a infinite stream if that is what you would like, you could do 

``` js
function main({storage}) {
  storage.getItem('key').take(1)
}
```

The best way (I know of) to achieve a continuous stream is to use a Subject. I'm not saying my solution is correct or the best, but maybe you can derive some inspiration from the [driver](https://github.com/TylorS/cycle-local-storage) that I wrote.

**Comment by TylorS** [comment]
@staltz :+1:

**Comment by TylorS** [comment]
@kahlil I definitely believe that it could be designed much better than I did it, I made that very quickly, and was still learning (still am!).

**Comment by khalillechelt** [comment]
@TylorS @staltz ahh, it all makes sense now. Thanks. Yes, a Subject would help me there... I will definitely have a look at your driver Tyler thanks!

**Comment by TylorS** [comment]
No problem, feel free to ask questions if you need any help along the way.

**Comment by khalillechelt** [comment]
Will do!

**Comment by khalillechelt** [comment]
Hey @staltz & @TylorS I was fooling around with this a bit and this seems to work: 
1. I pass in `request$` to the `responseCollection` like so: https://github.com/cyclejs/cycle-storage-driver/blob/streaming-updates/src/index.js#L48
2. then I just return that same stream back to the ui depending on which `key` is requested like so: https://github.com/cyclejs/cycle-storage-driver/blob/streaming-updates/src/responseCollection.js#L17-L25

Seem pretty straightforward and elegant to me, it also seems to work right in my test. Am I overlooking something? It seems so simple :smile:

**Comment by TylorS** [comment]
That looks like it should do the trick. I'm totally unfamiliar with sessionStorage but would it be a good idea to do the same for it as you did for localStorage?

**Comment by khalillechelt** [comment]
Yeah sessionStorage is exactly the same API as localStorage the data is just cleared after the session ends.

**Comment by laszlokorte** [comment]
The 1.1.0 release of storage broke my app.

I had something like the following set up:

``` javascript
const main = ({storage}) {
  const initialValue$ = storage.local.get('myCounter');
  const myCounter = Counter({initialValue$});
  const storageRequests$ = myCounter.values$;
  return {
      storage: storageReq$
   }
}
```

Which loads the initial value of the counter from the storage and requests to save all value changes of the counter back to the storage.

Now that the storage save requests a propagated back into the storage responses this creates and infinity cycle of counter updates. This can be solved by calling `take(1)` as described above.

``` javascript
const initialValue$ = storage.local.get('myCounter').take(1);
```

For me the error was very hard to locate because no error has been logged and the 1.1.0 tag of this storage module is only set in another branch.
Probably the major version should have been incremented for such a change.

**Comment by khalillechelt** [comment]
Damn, @laszlokorte zlokorte you are 100% right! I am so sorry messing up your app 🙁

**Comment by kahlil** [comment]
I mean @laszlokorte of course ^

**Comment by laszlokorte** [comment]
It's alright. It's just an example application I am playing around with. It just took me some time to track down the error because there was no error message reporting the cycle of streams but just a white screen :smile:
