### ISSUE TITLE
getItem empty items

### ISSUE THREAD

**Issue by laszlokorte** [kahlil/cycle-storage-driver#9]
Currently if there is nothing stored for a key the stream returned by `Storage.local.getItem('foo')` emits an empty string as item.

Now I want to load something from the storage but use a default value if nothing is stored yet. So I use this code:

``` javascript
const currentValue = Storage.local
    .getItem('foo')
    .take(1)
    .filter((v) => !!v) // get rid of empty item
    .map(parseInt)
    .startWith(42)
    .last();
```

The filter is needed to get rid of the empty value emitted from the store.

The choice of emitting an empty string (instead of false, 0, null or -1) seems pretty arbitrary and I can not image a case in which it would be desired to process this value (except for filtering it out)

So I propose if there is nothing stored for the requested key no Item should be emitted.
This would allow getting rid of the manual filtering and would allow the use if operators like DefaultIfEmpty:

``` javascript
const currentValue = Storage.local
    .getItem('foo')
    .take(1)
    .map(parseInt)
    .defaultIfEmpty(42);
```

**Comment by khalillechelt** [comment]
Good point! Can you send a PR?

**Comment by khalillechelt** [comment]
I have some time for this now, so I will take care of it. Thanks for the suggestion!

**Comment by laszlokorte** [comment]
ok

**Comment by khalillechelt** [comment]
new version published!
